base.url=https://www.cleartrip.com

mail.recipients= anurag10upadhyay@gmail.com
mail.subject=[PROD] Automation Report
mail.sender=upanu1012@gmail.com
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=upanu1012@gmail.com
mail.smtp.password=Akhil@1010   # or keep in env variable