base.url=https://uat.expedia.com
db.url=jdbc:mysql://uat-db:3306/test

mail.recipients=uat-managers@expedia.com
mail.subject=[UAT] Automation Report
mail.sender=automation.bot@expedia.com
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=automation.bot@expedia.com
mail.smtp.password=your_app_password
